"""Nullable false for username

Revision ID: 019abda9d59a
Revises: efe45f8274af
Create Date: 2025-07-27 14:50:29.848550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019abda9d59a'
down_revision = 'efe45f8274af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
