"""adds car and inventory tables

Revision ID: 0461c8330c6a
Revises: b4774b10e541
Create Date: 2025-05-13 15:14:35.299280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0461c8330c6a'
down_revision = 'b4774b10e541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_car_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vin_number', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('is_sold', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin_number')
    )
    op.create_table('car_inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('vin_number', sa.String(), nullable=False),
    sa.Column('is_submitted', sa.Boolean(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('sold_price', sa.Float(), nullable=True),
    sa.Column('sales_price', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('is_sold', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin_number')
    )
    op.create_table('car_edit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_inventory_id', sa.Integer(), nullable=False),
    sa.Column('field_changed', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('edited_by', sa.Integer(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['car_inventory_id'], ['car_inventories.id'], ),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('car_inventory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_inventory_id'], ['car_inventories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_photos')
    op.drop_table('car_edit_logs')
    op.drop_table('car_inventories')
    op.drop_table('master_car_records')
    # ### end Alembic commands ###
