"""Adds long and lat; adds join table to own multiple dealers

Revision ID: 04e6653eb00c
Revises: e49246e2b655
Create Date: 2025-08-16 13:53:22.987400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04e6653eb00c'
down_revision = 'e49246e2b655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_dealers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_group_id'], ['account_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'account_group_id')
    )
    with op.batch_alter_table('account_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_password_reset_token_key', type_='unique')
        batch_op.drop_column('token_expires_at')
        batch_op.drop_column('password_reset_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('users_password_reset_token_key', ['password_reset_token'])

    with op.batch_alter_table('account_groups', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    op.drop_table('owner_dealers')
    # ### end Alembic commands ###
