"""adds stripe functionality

Revision ID: 226702b44161
Revises: 332ad3d03642
Create Date: 2025-07-31 01:08:41.273610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226702b44161'
down_revision = '332ad3d03642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['stripe_customer_id'])
        batch_op.create_unique_constraint(None, ['stripe_subscription_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
