"""Adds constrains to db

Revision ID: 4200919d6bdb
Revises: 78b580e32c15
Create Date: 2025-09-25 12:10:46.058341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4200919d6bdb'
down_revision = '78b580e32c15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_groups', schema=None) as batch_op:
        batch_op.drop_constraint('account_groups_stripe_customer_id_key', type_='unique')
        batch_op.drop_constraint('account_groups_stripe_subscription_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_account_groups_stripe_customer_id'), ['stripe_customer_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_account_groups_stripe_subscription_id'), ['stripe_subscription_id'], unique=True)
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('car_inventories', schema=None) as batch_op:
        batch_op.create_index('ix_car_inv_group_created', ['account_group_id', 'created_at'], unique=False)
        batch_op.create_index('ix_car_inv_group_vin', ['account_group_id', 'vin_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_inventories_vin_number'), ['vin_number'], unique=False)

    with op.batch_alter_table('designated_locations', schema=None) as batch_op:
        batch_op.create_index('ix_designated_location_group', ['account_group_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_account_group', ['account_group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_account_group')

    with op.batch_alter_table('designated_locations', schema=None) as batch_op:
        batch_op.drop_index('ix_designated_location_group')

    with op.batch_alter_table('car_inventories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_inventories_vin_number'))
        batch_op.drop_index('ix_car_inv_group_vin')
        batch_op.drop_index('ix_car_inv_group_created')

    with op.batch_alter_table('account_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_account_groups_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_account_groups_stripe_customer_id'))
        batch_op.create_unique_constraint('account_groups_stripe_subscription_id_key', ['stripe_subscription_id'])
        batch_op.create_unique_constraint('account_groups_stripe_customer_id_key', ['stripe_customer_id'])

    # ### end Alembic commands ###
