"""removes birds table

Revision ID: 497184abea92
Revises: a35b4d039853
Create Date: 2025-06-11 18:55:12.124170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497184abea92'
down_revision = 'a35b4d039853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birds')
    with op.batch_alter_table('master_car_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('trim', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('body_style', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('interior_color', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('transmission', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('drivetrain', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('engine', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('fuel_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date_acquired', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_sold', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('mileage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_car_records', schema=None) as batch_op:
        batch_op.drop_column('mileage')
        batch_op.drop_column('date_sold')
        batch_op.drop_column('date_acquired')
        batch_op.drop_column('fuel_type')
        batch_op.drop_column('engine')
        batch_op.drop_column('drivetrain')
        batch_op.drop_column('transmission')
        batch_op.drop_column('interior_color')
        batch_op.drop_column('color')
        batch_op.drop_column('body_style')
        batch_op.drop_column('trim')
        batch_op.drop_column('model')

    op.create_table('birds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('species', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='birds_pkey')
    )
    # ### end Alembic commands ###
