"""adds inventory tables

Revision ID: 4ba6366ce859
Revises: d465be146674
Create Date: 2025-05-14 11:31:37.429587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba6366ce859'
down_revision = 'd465be146674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('submitted', sa.Boolean(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('car_inventories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_inventory_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user_inventories', ['user_inventory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_inventories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_inventory_id')

    op.drop_table('user_inventories')
    # ### end Alembic commands ###
