"""working on flask env error

Revision ID: 4e04712636f7
Revises: c93a14d1aa19
Create Date: 2025-05-06 15:16:19.792746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e04712636f7'
down_revision = 'c93a14d1aa19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
