"""Adds last_login

Revision ID: 50bfbc59aaf8
Revises: 5ca558aa0726
Create Date: 2025-10-09 23:54:28.748176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50bfbc59aaf8'
down_revision = '5ca558aa0726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_throttles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_throttles', schema=None) as batch_op:
        batch_op.create_index('ix_auth_throttle_lookup', ['user_id', 'email', 'ip_address', 'device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_throttles_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_throttles_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_throttles_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_throttles_locked_until'), ['locked_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_throttles_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_last_login_at'), ['last_login_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_last_login_at'))
        batch_op.drop_column('last_login_at')

    with op.batch_alter_table('auth_throttles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_throttles_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_throttles_locked_until'))
        batch_op.drop_index(batch_op.f('ix_auth_throttles_ip_address'))
        batch_op.drop_index(batch_op.f('ix_auth_throttles_email'))
        batch_op.drop_index(batch_op.f('ix_auth_throttles_device_id'))
        batch_op.drop_index('ix_auth_throttle_lookup')

    op.drop_table('auth_throttles')
    # ### end Alembic commands ###
