"""Removes nullable revision for user active

Revision ID: 5ca558aa0726
Revises: 4200919d6bdb
Create Date: 2025-10-02 20:39:32.732519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca558aa0726'
down_revision = '4200919d6bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index('ix_users_is_active', ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_is_active')
        batch_op.drop_column('deactivated_at')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
