"""updates for stripe

Revision ID: 5e53f1afea55
Revises: ba6994c86866
Create Date: 2025-10-21 13:19:55.689288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e53f1afea55'
down_revision = 'ba6994c86866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payment_intent_id', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_stripe_payment_intent_id'), ['stripe_payment_intent_id'], unique=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_payment_provider_reference', ['provider', 'reference'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_payment_provider_reference', type_='unique')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_stripe_payment_intent_id'))
        batch_op.drop_column('stripe_payment_intent_id')

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('closed_at')

    # ### end Alembic commands ###
