"""Adds Long and Lat to car and car details

Revision ID: 78b580e32c15
Revises: dae15d7857bf
Create Date: 2025-08-24 16:12:10.603367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b580e32c15'
down_revision = 'dae15d7857bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_inventories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('body', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_inventories', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('body')
        batch_op.drop_column('color')

    # ### end Alembic commands ###
