"""Enforce nullable false

Revision ID: 790663a43e3f
Revises: 9c8cf70ed1b0
Create Date: 2025-07-26 15:17:29.103234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790663a43e3f'
down_revision = '9c8cf70ed1b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_inventories', schema=None) as batch_op:
        batch_op.alter_column('account_group_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user_inventories', schema=None) as batch_op:
        batch_op.alter_column('account_group_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('account_group_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('account_group_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user_inventories', schema=None) as batch_op:
        batch_op.alter_column('account_group_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('car_inventories', schema=None) as batch_op:
        batch_op.alter_column('account_group_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
