"""updates photos and change relationship to master inventory

Revision ID: 97286a88a524
Revises: 497184abea92
Create Date: 2025-06-13 00:30:14.633964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97286a88a524'
down_revision = '497184abea92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('master_car_record_id', sa.Integer(), nullable=True))
        batch_op.alter_column('car_inventory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'master_car_records', ['master_car_record_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_photos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('car_inventory_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('master_car_record_id')

    # ### end Alembic commands ###
