"""Add account_group_id as nullable

Revision ID: 9c8cf70ed1b0
Revises: 97286a88a524
Create Date: 2025-07-26 15:14:57.066476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8cf70ed1b0'
down_revision = '97286a88a524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_key', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('paid_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_key')
    )
    with op.batch_alter_table('car_inventories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'account_groups', ['account_group_id'], ['id'])

    with op.batch_alter_table('user_inventories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'account_groups', ['account_group_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_owner_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('account_group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'account_groups', ['account_group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('account_group_id')
        batch_op.drop_column('is_owner_admin')

    with op.batch_alter_table('user_inventories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('account_group_id')

    with op.batch_alter_table('car_inventories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('account_group_id')

    op.drop_table('account_groups')
    # ### end Alembic commands ###
