"""updates inventory table constrains

Revision ID: a35b4d039853
Revises: 4ba6366ce859
Create Date: 2025-05-19 17:48:15.317520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35b4d039853'
down_revision = '4ba6366ce859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_inventories', schema=None) as batch_op:
        batch_op.drop_constraint('car_inventories_vin_number_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_inventories', schema=None) as batch_op:
        batch_op.create_unique_constraint('car_inventories_vin_number_key', ['vin_number'])

    # ### end Alembic commands ###
