"""working on 409 error

Revision ID: caa5d5bcaf6d
Revises: 8c2e0e90fdf0
Create Date: 2025-10-21 22:55:25.256043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa5d5bcaf6d'
down_revision = '8c2e0e90fdf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_sessions', schema=None) as batch_op:
        batch_op.alter_column('stripe_session_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('stripe_client_secret',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_sessions', schema=None) as batch_op:
        batch_op.alter_column('stripe_client_secret',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('stripe_session_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
