"""Adds notes table

Revision ID: d12cd9b23846
Revises: 04e6653eb00c
Create Date: 2025-08-19 10:35:13.973104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12cd9b23846'
down_revision = '04e6653eb00c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_inventory_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['car_inventory_id'], ['car_inventories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_notes')
    # ### end Alembic commands ###
