"""re-structure models and removes editlogs

Revision ID: d465be146674
Revises: 0461c8330c6a
Create Date: 2025-05-14 11:10:00.677414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd465be146674'
down_revision = '0461c8330c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_edit_logs')
    with op.batch_alter_table('car_inventories', schema=None) as batch_op:
        batch_op.drop_column('is_submitted')
        batch_op.drop_column('is_reviewed')
        batch_op.drop_column('sales_price')
        batch_op.drop_column('purchase_price')
        batch_op.drop_column('is_sold')
        batch_op.drop_column('sold_price')

    with op.batch_alter_table('master_car_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selling_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sold_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_car_records', schema=None) as batch_op:
        batch_op.drop_column('sold_price')
        batch_op.drop_column('selling_price')

    with op.batch_alter_table('car_inventories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_sold', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('purchase_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sales_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_reviewed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_submitted', sa.BOOLEAN(), autoincrement=False, nullable=True))

    op.create_table('car_edit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('car_inventory_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('field_changed', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('old_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('new_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('edited_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('edited_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['car_inventory_id'], ['car_inventories.id'], name='car_edit_logs_car_inventory_id_fkey'),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], name='car_edit_logs_edited_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='car_edit_logs_pkey')
    )
    # ### end Alembic commands ###
