"""adds sesignated locations

Revision ID: dae15d7857bf
Revises: d92a057eaf50
Create Date: 2025-08-24 11:47:28.466473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae15d7857bf'
down_revision = 'd92a057eaf50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designated_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('account_group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_group_id'], ['account_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('car_inventories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designated_location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'designated_locations', ['designated_location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_inventories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('designated_location_id')

    op.drop_table('designated_locations')
    # ### end Alembic commands ###
