"""adds user's name

Revision ID: efe45f8274af
Revises: ed50ccb72b98
Create Date: 2025-07-27 14:48:00.251682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe45f8274af'
down_revision = 'ed50ccb72b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=True))
        batch_op.drop_column('fist_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fist_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
